# Generated by Django 3.2.6 on 2021-08-26 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frequencyWorkshop', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FFTFiles',
        ),
    ]
